CREATE SEQUENCE character_seq START 1;
CREATE SEQUENCE comic_seq START 1;
CREATE SEQUENCE creator_seq START 1;
CREATE SEQUENCE event_seq START 1;
CREATE SEQUENCE series_seq START 1;
CREATE SEQUENCE story_seq START 1;